### ISSUE TITLE
Force Field

### ISSUE THREAD

**Issue by baba-hashimoto** [simongravelle/PEGgenerator#2]
Thank you for creating a great tool. I have a question about classical force fields.
Is the force field used in this program charmm35r.itp?
It looks different from the forcefield described in https://github.com/simongravelle/gromacs-input-files/tree/main/PEG-in-vacuum/ff.
I don't have much experience with charmm force fields and asked a rudimentary question.

**Comment by simongravelle** [comment]
Hello, 
It is charmm36, you can find the parameters here :   
https://github.com/simongravelle/PEGgenerator/tree/main/ff
Feel free to modify them before running the code, then you can have the force field you want.
Best,
Simon

**Comment by baba-hashimoto** [comment]
Thank you for your immediate response. It is good to know the type of force field.
